In [9]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import matplotlib.pyplot as plt
import geopandas as gpd

In [10]:
all = pd.read_csv('World Important Dates.csv', na_values='Unknown')
all.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,NaN,NaN,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,NaN,NaN,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,NaN,NaN,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

In [11]:
all.columns

Index(['Sl. No', 'Name of Incident', 'Date', 'Month', 'Year', 'Country',
       'Type of Event', 'Place Name', 'Impact', 'Affected Population',
       'Important Person/Group Responsible', 'Outcome'],
      dtype='object')

In [12]:
all.Country.unique()

array(['India', 'UK', 'Pakistan', 'Sri Lanka', 'China', 'Russia', 'USSR',
       'Japan', 'Australia', 'New Zealand', 'Korea', 'South Korea',
       'North Korea', 'Vietnam', 'Saudi Arabia', 'Singapore', 'Iran',
       'Iraq', 'Almaty', 'Bukhara', 'Bhutan', 'Maldives', 'Malaya',
       'Tehran', 'Kazakhstan', 'Samarkand', 'Thimphu', 'Malaysia',
       'Babylon', 'Malacca', 'Persia', 'Uzbekistan', 'Central Asia',
       'Basra', 'Tashkent', 'Punakha', 'Soviet Union', 'Uzbek SSR',
       'Addu Atoll', 'Kuwait, Iraq', 'Mosul', 'Zhanaozen', 'Taiwan',
       'Indonesia', 'Philippines', 'Thailand', 'USA', 'Canada', 'France',
       'Italy', 'Spain', 'Spain/USA', 'South Africa', 'England',
       'Gibraltar', 'Denmark', 'Norway', 'Finland', 'Nigeria', 'Kenya',
       'Algeria', 'Libya', 'Tunisia', 'Zimbabwe', 'Morocco', 'Angola',
       'Egypt', 'Rwanda', 'Uganda', 'Somalia', 'Botswana', 'Namibia',
       'Sudan', "Côte d'Ivoire", 'Ghana', 'Tanzania', 'Madagascar',
       'Ethiopia', 'Mozambique', 'Zambia', 'Senegal', 'Congo (DRC)',
       'Sierra Leone', 'Mali', 'Burkina Faso', 'Cameroon', 'Eritrea',
       'Benin', 'Mauritania', 'Gabon', 'Lesotho', 'Gambia', 'Djibouti',
       'Equatorial Guinea', 'Seychelles', 'Cape Verde',
       'GuineaUnknownBissau', 'Comoros', 'Central African Republic',
       'Chad', 'Malawi', 'Burundi', 'Congo (Brazzaville)', 'Togo',
       "Ivory Coast (Côte d'Ivoire)", 'Niger', 'Swaziland (Eswatini)',
       'Guinea', 'South Sudan', 'Brazil', 'Germany', 'Argentina',
       'Mexico'], dtype=object)

In [13]:
country_corrections = {
    "USSR": "Russia",
    "UK": "United Kingdom",
    "Soviet Union": "Russia", 
    "Uzbek SSR": "Uzbekistan",
    "Malaya": "Malaysia", 
    "Persia": "Iran", 
    "Babylon": "Iraq",
    "England": "United Kingdom", 
    "Spain/USA": "Multiple", 
    "Kuwait, Iraq": "Multiple",
    "Congo (DRC)": "Democratic Republic of the Congo", 
    "Congo (Brazzaville)": "Republic of the Congo",
    "Ivory Coast (Côte d'Ivoire)": "Côte d'Ivoire", 
    "Swaziland (Eswatini)": "Eswatini",
    "GuineaUnknownBissau": "Guinea-Bissau", 
    "USA": "United States of America", 
    "Vietnam": "Vietnam",
    "Almaty": "Kazakhstan", 
    "Bukhara": "Uzbekistan", 
    "Samarkand": "Uzbekistan",
    "Tehran": "Iran", 
    "Tashkent": "Uzbekistan", 
    "Thimphu": "Bhutan",
    "Basra": "Iraq", 
    "Mosul": "Iraq", 
    "Zhanaozen": "Kazakhstan",
    "Addu Atoll": "Maldives",
    'UAE': 'United Arab Emirates',
    'Central African Republic': 'Central African Rep.',
    'South Sudan': 'S. Sudan',
    'Equatorial Guinea': 'Eq. Guinea'
}

all['Country'] = all['Country'].replace(country_corrections)

all['Country'].unique()

array(['India', 'United Kingdom', 'Pakistan', 'Sri Lanka', 'China',
       'Russia', 'Japan', 'Australia', 'New Zealand', 'Korea',
       'South Korea', 'North Korea', 'Vietnam', 'Saudi Arabia',
       'Singapore', 'Iran', 'Iraq', 'Kazakhstan', 'Uzbekistan', 'Bhutan',
       'Maldives', 'Malaysia', 'Malacca', 'Central Asia', 'Punakha',
       'Multiple', 'Taiwan', 'Indonesia', 'Philippines', 'Thailand',
       'United States of America', 'Canada', 'France', 'Italy', 'Spain',
       'South Africa', 'Gibraltar', 'Denmark', 'Norway', 'Finland',
       'Nigeria', 'Kenya', 'Algeria', 'Libya', 'Tunisia', 'Zimbabwe',
       'Morocco', 'Angola', 'Egypt', 'Rwanda', 'Uganda', 'Somalia',
       'Botswana', 'Namibia', 'Sudan', "Côte d'Ivoire", 'Ghana',
       'Tanzania', 'Madagascar', 'Ethiopia', 'Mozambique', 'Zambia',
       'Senegal', 'Democratic Republic of the Congo', 'Sierra Leone',
       'Mali', 'Burkina Faso', 'Cameroon', 'Eritrea', 'Benin',
       'Mauritania', 'Gabon', 'Lesotho', 'Gambia', 'Djibouti',
       'Eq. Guinea', 'Seychelles', 'Cape Verde', 'Guinea-Bissau',
       'Comoros', 'Central African Rep.', 'Chad', 'Malawi', 'Burundi',
       'Republic of the Congo', 'Togo', 'Niger', 'Eswatini', 'Guinea',
       'S. Sudan', 'Brazil', 'Germany', 'Argentina', 'Mexico'],
      dtype=object)

In [14]:
all['Place Name'].unique()

array(['Indus Valley', 'Punjab', 'Delhi', 'Panipat', 'Whole India',
       'India/Pakistan', 'Bangladesh', 'Pokhran', 'Mumbai', 'Calicut',
       'Plassey', 'Meerut', 'Bengal', 'Punjab, Haryana', 'Amritsar',
       'Kargil, Ladakh', 'India', 'New Delhi', 'Ayodhya', 'Maharashtra',
       'Border regions of India', 'Pokhran, Rajasthan',
       'Bhopal, Madhya Pradesh', 'Kandahar, Afghanistan',
       'Jammu & Kashmir', 'Gujarat', 'Uttar Pradesh', "Lord's, England",
       'Uttarakhand', 'Mars', 'South Africa', 'Nationwide', 'Moon',
       'Pulwama, Jammu and Kashmir', 'Paris, France',
       'Uri, Jammu and Kashmir', 'Bombay', 'Chauri Chaura', 'Dandi',
       'London', 'Lahore', 'Various', 'Calcutta (now Kolkata)',
       'Bangalore', 'Agra', 'Pakistan', 'Kashmir', 'New York', 'Dhaka',
       'East Pakistan', 'Chagai, Balochistan', 'Kargil, Kashmir',
       'Kashmir, Pakistan', 'Rawalpindi', 'North Waziristan', 'Peshawar',
       'Islamabad', 'Kartarpur', 'Federally Administered Tribal Areas',
       'Pulwama, India', 'Siachen Glacier', 'Karachi', 'Oslo, Norway',
       'Khunjerab Pass to Hassan Abdal', 'Xichang, China', 'Gwadar',
       'Colombo', 'Sri Lanka', 'Colombo, others', 'Coastal Sri Lanka',
       'Mullaitivu', 'Mahaweli River', 'Sigiriya', 'Imperial court',
       'Han Dynasty China', 'Northern China', "Chang'an", 'Kaifeng',
       'Mongol Empire', 'China', 'Nanjing', 'Southern China', 'Wuchang',
       'Jiangxi to Shaanxi', 'Hong Kong', 'Beijing',
       'China to the Mediterranean', 'Yangtze River',
       'Hangzhou to Beijing', 'Southeast Asia, Africa', 'Macau',
       'Shanghai', "Chang'an, Luoyang", 'Yuan Dynasty China',
       'Ming Dynasty China', 'Nanking', 'Beijing, Shanghai', 'Geneva',
       'Guangdong', 'South China Sea', 'Brussels', 'Kiev', "Kievan Rus'",
       'Kulikovo Field', 'Moscow', 'Russia', 'Manchuria, Korea',
       'Petrograd (Saint Petersburg)', 'Soviet Union',
       'BrestUnknownLitovsk (now Brest, Belarus)', 'Kronstadt',
       'Soviet Russia', 'Finland', 'Leningrad (now Saint Petersburg)',
       'Stalingrad (now Volgograd)', 'Yalta, Crimea',
       'Baikonur Cosmodrome', 'Cuba', 'Czechoslovakia', 'Afghanistan',
       'Chernobyl, Ukraine', 'Berlin, Germany', 'Beslan, North Ossetia',
       'Crimea', 'Syria', 'Salisbury, UK', 'Asuka', 'Japan', 'Nara',
       'HeianUnknownkyō (Kyoto)', 'Kamakura', 'Kyushu',
       'Muromachi, Kyoto', 'Kyoto', 'Tanegashima', 'Azuchi',
       'Edo (Tokyo)', 'Korea, China', 'Manchuria, China',
       'Hiroshima, Nagasaki', 'Edo Bay (Tokyo Bay)', 'USA, Europe',
       'Korea', 'Washington D.C.', 'Near Beijing, China', 'Tokyo Bay',
       'San Francisco', 'Tokyo', 'Osaka', 'Kobe', 'Fukushima', 'Seoul',
       'Sydney Cove', 'Tasmania', 'New South Wales, Victoria',
       'Ballarat, Victoria', 'Entire Australia', 'Gallipoli, Turkey',
       'Sydney', 'Darwin, Northern Territory', 'Papua New Guinea',
       'Global', 'Myall Creek, New South Wales', 'Melbourne, Victoria',
       'Queensland', 'Australia', 'Victoria', 'High Court of Australia',
       'Vietnam', 'Canberra', 'Port Arthur, Tasmania', 'Canberra, London',
       'Northern Territory', 'Australia, UK', 'Indian Ocean', 'Waitangi',
       'Various locations', 'Otago, West Coast', nan, 'Tarawera',
       'Europe, Pacific', 'Auckland', 'New Zealand', 'Christchurch',
       'Kyoto, Japan', 'Korean Peninsula', 'Gyeongbokgung Palace',
       'Korean Peninsula, Manchuria', 'Shanghai, China',
       '38th Parallel North', 'Pyongyang', 'Jeju Island', 'South Korea',
       'North Korea', 'Panmunjom', 'Sea of Japan', 'Kilju County',
       'Gwangju', 'South Korea, Japan', 'Seongju County', 'Điện Biên Phủ',
       'South Vietnam', 'Gulf of Tonkin', 'Paris', 'Saigon',
       'Vietnam, US', 'Southeast Asia', 'Hanoi', 'Da Nang', 'Space',
       'Hanoi, Ho Chi Minh City', 'Northern Vietnam', 'Southern Vietnam',
       'Central Vietnam', 'Yên Bái', 'Ba Đình Square, Hanoi', 'Diriyah',
       'Najd', 'Hejaz', 'Najd, Hejaz', 'Jeddah', 'Dammam', 'Dhahran',
       'Saudi Arabia', 'Yemen border', 'Mecca', 'Riyadh', 'Taif',
       'Middle East', 'Eastern Province', 'Cairo', 'Persian Gulf',
       'Kuwait, Saudi Arabia', 'Yemen', 'Istanbul, Turkey', 'Singapore',
       'Malaya', 'Malaysia', 'Sentosa', 'Iran', 'Mesopotamia',
       'Kazakhstan', 'Bukhara', 'Punakha', 'Maldives', 'Iraq',
       'Samarkand', 'Thimphu', 'Babylon', 'Bhutan', 'Malacca', 'Persia',
       'Baghdad', 'Uzbekistan', 'Northern Kazakhstan', 'Kengir',
       'Central asia', 'Peninsular', 'Basra', 'Tashkent', 'Addu Atoll',
       'Iraq/Iran border', 'From Almaty to Astana', 'Astana',
       'Kuala Lumpur', 'Mosul', 'Zhanaozen', 'Malé', 'NurUnknownSultan',
       'Southern Indian Ocean', 'Mount Takamagahara', 'Taiwan Strait',
       'Guam', 'Java Sea', 'Kathmandu', 'Okinawa', 'Musi River', 'Phuket',
       'Yellow Sea', 'Fukushima Prefecture', 'Wenzhou', 'Tablas Strait',
       'Sidoarjo', 'Tham Luang Cave', 'Philadelphia', 'Midwest',
       'Southern USA', 'Wall Street, NY', 'NY, VA, PA', 'Topeka, Kansas',
       'Cape Canaveral, FL', 'Oklahoma City, OK', 'Gulf Coast',
       'USUnknownMexico Border', 'International', 'East Coast',
       'Dallas, Texas', 'New York, NY', 'Silicon Valley, CA',
       'Charlottesville, VA', 'Boston, MA', 'Western USA', 'California',
       'Seneca Falls, NY', 'Confederate States', 'Promontory, Utah',
       'Cuba, Philippines', 'Kitty Hawk, NC', 'Southwestern USA',
       'Supreme Court', 'Western Territories', 'Panama', 'Europe',
       'Pearl Harbor, HI', 'Western Europe', 'San Francisco, CA',
       'Jamestown, VA', 'Salem, MA', 'Eastern North America',
       'USA, Canada', 'Missouri', 'Southeastern USA', 'Kansas, Nebraska',
       'Alaska', 'Ottawa', 'Vimy Ridge, France', 'Toronto',
       'Newfoundland', 'Oka, Quebec', 'Vancouver', 'Fort McMurray, AB',
       'Northern Canada', 'Quebec', 'Red River Colony', 'Yukon',
       'Halifax, NS', 'British Columbia', 'Leduc, Alberta', 'London, UK',
       'Runnymede', 'English Channel', 'England', 'Scotland and England',
       'Trafalgar', 'Parliament', 'Suez Canal', 'Liverpool',
       'Falkland Islands', 'Northern Ireland', 'UK',
       'Stockton to Darlington', 'Skies over Britain', 'Aldermaston',
       'Scotland', 'London and nationwide', 'Windsor', 'France',
       'Waterloo', "St Mary's Hospital", 'Westminster Abbey',
       'Roslin Institute', 'Gleneagles', 'Salisbury Plain', 'Oxford',
       'Agincourt', 'Derry', 'Tours', 'Verdun', 'Rome', 'Clermont',
       'Orléans', 'Nantes', 'Clermont (announced)', 'Lodi',
       'Constantinople (Impact on Italy)', 'Florence', 'Venice',
       'Utrecht (Impact on Italy)', 'Turin', 'Milan', "L'Aquila",
       'Giglio Island', 'Atlantic Ocean', 'Granada', 'Pyrenees',
       'Caribbean, Pacific', 'Spain', 'Madrid',
       'Cuba, Philippines, Puerto Rico, Guam', 'Americas',
       'Atlantic Ocean near Cape Trafalgar', 'Utrecht',
       'Iberian Peninsula', 'Cadiz', 'Barcelona', 'Catalonia',
       'Valle de los Caídos', 'Basque Country', 'Altamira', 'Worldwide',
       'Johannesburg', 'Between MadridUnknownSeville', 'Gibraltar',
       'Spanish America', 'Gadir (Cádiz)', 'Guadalete River', 'Denmark',
       'Norway', 'Kalmar, Sweden', 'Roskilde', 'Copenhagen', 'Lapland',
       'Schleswig', 'Oslo', 'Fredrikshamn', 'Kimberley', 'Nigeria',
       'Kenya', 'Algeria', 'Libya', 'Tunisia', 'Great Zimbabwe',
       'Marrakech', 'Angola', 'Rwanda', 'Uganda', 'Somalia', 'Botswana',
       'Namibia', 'Sudan', "Côte d'Ivoire", 'Ghana', 'Tanzania',
       'Madagascar', 'Ethiopia', 'Sharpeville', 'Algiers', 'Mozambique',
       'Zambia', 'Senegal', 'Congo (DRC)', 'Sierra Leone', 'Mali',
       'Burkina Faso', 'Zimbabwe', 'Egypt', 'Cameroon', 'Eritrea',
       'Arusha, Tanzania', 'Benin (Dahomey)', 'Mauritania', 'Gabon',
       'Lesotho', 'Gambia', 'Djibouti', 'Equatorial Guinea', 'Seychelles',
       'Cape Verde', 'GuineaUnknownBissau', 'Comoros',
       'Central African Republic', 'Chad', 'Malawi', 'Burundi',
       'Congo (Brazzaville)', 'Togo', 'Ivory Coast', 'Niger', 'Swaziland',
       'Guinea', 'Rome, Italy', 'Northern Uganda', 'Sirte, Libya',
       'Cairo, Egypt', 'Bamako, Mali', 'Northeast Nigeria', 'South Sudan',
       'Ouagadougou, Burkina Faso', 'Harare, Zimbabwe', 'Nairobi, Kenya',
       'Mozambique, Zimbabwe, Malawi', 'Tigray, Ethiopia',
       'Juba, South Sudan', 'Coast of presentUnknownday Brazil',
       'São Paulo', 'Brazil', 'Rio de Janeiro', 'Sweden', 'Brasília',
       'Amazon Rainforest', 'Germany', 'Wittenberg', 'Augsburg', 'Prague',
       'Münster and Osnabrück', 'Königsberg', 'Poland', 'Leipzig',
       'Vienna', 'German states', 'Versailles', 'France/Germany',
       'Poland/Germany', 'Stalingrad (Volgograd)', 'Normandy',
       'Reims/Berlin', 'West Germany', 'Berlin', 'Maastricht',
       'Buenos Aires', 'Tucumán', 'Patagonia', 'Argentina',
       'Vatican City', 'Near Mexico City', 'Yucatán Peninsula',
       'Teotihuacan', 'Lake Texcoco', 'Tenochtitlán', 'Mexico', 'Dolores',
       'Córdoba', 'Northern Mexico'], dtype=object)

In [15]:
place_corrections = {
    "Delhi": "New Delhi",
    "Whole India": "Countrywide",
    "India/Pakistan": "Multiple",
    "Calicut": "Kozhikode",
    "Plassey": "Palashi",
    "Lord's, England": "Lord's Cricket Ground, London",
    "Nationwide": "Countrywide",
    "Bombay": "Mumbai",
    "Calcutta (now Kolkata)": "Kolkata",
    "East Pakistan": "Countrywide",
    "Chauri Chaura": "Chauri Chaura, Uttar Pradesh",
    "Kashmir, Pakistan": "Azad Kashmir",
    "Federally Administered Tribal Areas": "Khyber Pakhtunkhwa",
    "Various": "Multiple",
    "Colombo, others": "Multiple",
    "Coastal Sri Lanka": "Countrywide",
    "Khunjerab Pass to Hassan Abdal": "Khunjerab Pass",
    "Han Dynasty China": "Countrywide", 
    "Yuan Dynasty China": "Countrywide", 
    "Ming Dynasty China": "Countrywide",
    "Chang'an": "Xi'an", 
    "Nanking": "Nanjing",
    "Mongol Empire": "Countrywide",
    "Kievan Rus'": "Multiple",
    "Petrograd (Saint Petersburg)": "Saint Petersburg",
    "BrestUnknownLitovsk (now Brest, Belarus)": "Brest",
    "Soviet Union": "Multiple",
    "Manchuria, Korea": "Countrywide",
    "China to the Mediterranean": "Multiple",
    "Southeast Asia, Africa": "Multiple",
    "Jiangxi to Shaanxi": "Multiple",
    "Hangzhou to Beijing": "Multiple",
    "Leningrad (now Saint Petersburg)": "Saint Petersburg",
    "Stalingrad (now Volgograd)": "Volgograd",
    "HeianUnknownkyō (Kyoto)": "Kyoto",
    "Edo (Tokyo)": "Tokyo",
    "Soviet Russia": "Countrywide",
    "Korea, China": "Multiple",
    "Manchuria, China": "Countrywide",
    "USA, Europe": "Multiple",
    "Korea": "Countrywide",
    "Near Beijing, China": "Beijing",
    "Czechoslovakia": "Countrywide",
    "Beslan, North Ossetia": "Beslan",
    "Hiroshima": "Hiroshima",
    "Sydney Cove": "Sydney",
    "New South Wales, Victoria": "Multiple",
    "Entire Australia": "Countrywide",
    "Australia, UK": "Multiple",
    "Europe, Pacific": "Multiple",
    "Global": "Multiple",
    "Canberra, London": "Multiple",
    "Waitangi": "Waitangi",
    "Tarawera": "Mount Tarawera",
    "Otago, West Coast": "Multiple",
    "Kyoto, Japan": "Kyoto",
    "Gyeongbokgung Palace": "Gyeongbokgung Palace, Seoul",
    "Shanghai, China": "Shanghai",
    "Korean Peninsula, Manchuria": "Countrywide",
    "Vietnam, US": "Countrywide",
    "South Vietnam": "Countrywide",
    "North Vietnam": "Countrywide",
    "Central Vietnam": "Countrywide",
    "Southern Vietnam": "Countrywide",
    "Northern Vietnam": "Countrywide",
    "Najd, Hejaz": "Multiple",
    "Istanbul, Turkey": "Istanbul",
    "Eastern Province": "Countrywide",
    "Kuwait, Saudi Arabia": "Multiple",
    "Malaya": "Countrywide",
    "Mesopotamia": "Countrywide",
    "Persia": "Countrywide",
    "Peninsular": "Malay Peninsula",
    "Addu Atoll": "Addu Atoll",
    "Iraq/Iran border": "Multiple",
    "From Almaty to Astana": "Multiple",
    "Astana": "Nur-Sultan",
    "NurUnknownSultan": "Nur-Sultan",
    "Wall Street, NY": "Wall Street, New York",
    "USUnknownMexico Border": "US-Mexico Border",
    "Confederate States": "Southern United States",
    "Fukushima Prefecture": "Fukushima",
    "Cuba, Philippines": "Multiple",
    "Southwestern USA": "Southwestern United States",
    "Southeastern USA": "Southeastern United States",
    "USA, Canada": "Multiple",
    "Scotland and England": "Multiple",
    "Kansas, Nebraska": "Multiple",
    "Western Territories": "Multiple",
    "Supreme Court": "Supreme Court, Washington D.C.",
    "Trafalgar": "Cape Trafalgar",
    "Parliament": "Parliament, London",
    "London and nationwide": "London",
    "Stockton to Darlington": "Multiple",
    "Skies over Britain": "Space",
    "Constantinople (Impact on Italy)": "Istanbul",
    "Utrecht (Impact on Italy)": "Utrecht",
    "Caribbean, Pacific": "Multiple",
    "Cuba, Philippines, Puerto Rico, Guam": "Multiple",
    "Americas": "Multiple",
    "Between MadridUnknownSeville": "Multiple",
    "Spanish America": "Multiple",
    "Gadir (Cádiz)": "Cadiz",
    "Guadalete River": "Guadalete River",
    "Fredrikshamn": "Frederikshavn",
    "Benin (Dahomey)": "Countrywide",
    "Congo (DRC)": "Countrywide",
    "GuineaUnknownBissau": "Countrywide",
    "Congo (Brazzaville)": "Countrywide",
    "Ivory Coast": "Countrywide",
    "Swaziland": "Countrywide",
    "Königsberg": "Kaliningrad",
    "France/Germany": "Multiple",
    "Coast of presentUnknownday Brazil": "Brazilian Coast",
    "Mozambique, Zimbabwe, Malawi": "Multiple",
    "Poland/Germany": "Multiple",
    "Stalingrad (Volgograd)": "Volgograd",
    "Reims/Berlin": "Multiple",
    "West Germany": "Countrywide",
    "Near Mexico City": "Mexico City",
    "Tenochtitlán": "Mexico City",
    "Dolores": "Dolores Hidalgo",
    "Córdoba": "Córdoba, Veracruz",
    "Moon": "Space",
    "Mars": "Space",
    'India': 'Countrywide', 
    'United Kingdom': 'Countrywide',
    'UK': 'Countrywide',
    'Pakistan': 'Countrywide',
    'Sri Lanka': 'Countrywide', 
    'China': 'Countrywide',
    'Russia': 'Countrywide', 
    'Japan': 'Countrywide', 
    'Australia': 'Countrywide', 
    'New Zealand': 'Countrywide', 
    'Korea': 'Countrywide',
    'South Korea': 'Countrywide', 
    'North Korea': 'Countrywide', 
    'Vietnam': 'Countrywide', 
    'Saudi Arabia': 'Countrywide',
    'Singapore': 'Countrywide', 
    'Iran': 'Countrywide', 
    'Iraq': 'Countrywide', 
    'Kazakhstan': 'Countrywide', 
    'Uzbekistan': 'Countrywide', 
    'Bhutan': 'Countrywide',
    'Maldives': 'Countrywide',
    'Malaysia': 'Countrywide', 
    'Malacca': 'Countrywide', 
    'Central Asia': 'Countrywide', 
    'Punakha': 'Countrywide',
    'Taiwan': 'Countrywide', 
    'Indonesia': 'Countrywide', 
    'Philippines': 'Countrywide', 
    'Thailand': 'Countrywide',
    'United States': 'Countrywide',
    'USA': 'Countrywide', 
    'Canada': 'Countrywide', 
    'France': 'Countrywide', 
    'Italy': 'Countrywide', 
    'Spain': 'Countrywide',
    'South Africa': 'Countrywide',
    'Gibraltar': 'Countrywide', 
    'Denmark': 'Countrywide', 
    'Norway': 'Countrywide', 
    'Finland': 'Countrywide',
    'Nigeria': 'Countrywide', 
    'Kenya': 'Countrywide', 
    'Algeria': 'Countrywide', 
    'Libya': 'Countrywide', 
    'Tunisia': 'Countrywide', 
    'Zimbabwe': 'Countrywide',
    'Morocco': 'Countrywide', 
    'Angola': 'Countrywide', 
    'Egypt': 'Countrywide', 
    'Rwanda': 'Countrywide', 
    'Uganda': 'Countrywide', 
    'Somalia': 'Countrywide',
    'Botswana': 'Countrywide', 
    'Namibia': 'Countrywide', 
    'Sudan': 'Countrywide', 
    "Côte d'Ivoire": 'Countrywide', 
    'Ghana': 'Countrywide',
    'Tanzania': 'Countrywide', 
    'Madagascar': 'Countrywide', 
    'Ethiopia': 'Countrywide', 
    'Mozambique': 'Countrywide', 
    'Zambia': 'Countrywide',
    "Senegal": "Countrywide",
    "Democratic Republic of the Congo": "Countrywide",
    "Sierra Leone": "Countrywide",
    "Mali": "Countrywide",
    "Burkina Faso": "Countrywide",
    "Cameroon": "Countrywide",
    "Eritrea": "Countrywide",
    "Benin": "Countrywide",
    "Mauritania": "Countrywide",
    "Gabon": "Countrywide",
    "Lesotho": "Countrywide",
    "Gambia": "Countrywide",
    "Djibouti": "Countrywide",
    "Equatorial Guinea": "Countrywide",
    "Seychelles": "Countrywide",
    "Cape Verde": "Countrywide",
    "Guinea-Bissau": "Countrywide",
    "Comoros": "Countrywide",
    "Central African Republic": "Countrywide",
    "Chad": "Countrywide",
    "Malawi": "Countrywide",
    "Burundi": "Countrywide",
    "Republic of the Congo": "Countrywide",
    "Togo": "Countrywide",
    "Niger": "Countrywide",
    "Eswatini": "Countrywide",
    "Guinea": "Countrywide",
    "South Sudan": "Countrywide",
    "Brazil": "Countrywide",
    "Germany": "Countrywide",
    "Argentina": "Countrywide",
    "Mexico": "Countrywide"
}

all['Place Name'] = all['Place Name'].replace(place_corrections)

In [16]:
# Check the updated unique place names
all.dropna(subset=['Place Name'], inplace=True)
all.dropna(subset=['Country'], inplace=True)
all = all[~all['Place Name'].isin(['Multiple', 'Countrywide', 'Space'])]

In [17]:
# Make the year before Christ negative
all['Year'] = all['Year'].apply(lambda x: "-" + x.split(' ')[0] if 'BC' in x else x)
all['Year'] = pd.to_numeric(all['Year'], errors='coerce')
# Drop rows with missing years
all.dropna(subset=['Year'], inplace=True)

In [18]:
#copy the data
coord = all.copy()

In [ ]:
# Initialize the geocoder
geolocator = Nominatim(user_agent="geoapiRun1")

# To prevent hitting the service too hard, wrap the geolocator with a rate limiter
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=2)

# Function to apply to each row in the DataFrame
def geocode_place(row):
    # Combine the place name and country into one search query for more accurate results
    query = f"{row['Place Name']}, {row['Country']}"
    try:
        # Attempt to geocode using the combined query
        location = geocode(query)
        if location:
            return pd.Series([location.latitude, location.longitude])
        else:
            return pd.Series([None, None])
    except:
        return pd.Series([None, None])

# Apply the function to the DataFrame
coord[['latitude', 'longitude']] = coord.apply(geocode_place, axis=1)

In [4]:
# Initialize the geocoder for run two (on the data that failed in run one)
geolocator = Nominatim(user_agent="geoapiRun2")

# To prevent hitting the service too hard, wrap the geolocator with a rate limiter
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=2)

# Function to apply to each rowin the DataFrame
def geocode_place(row):
    # If the latitude is already known, return it
    if pd.notnull(row['latitude']):
        return pd.Series([row['latitude'], row['longitude']])
    # Combine the place name and country into one search query for more accurate results
    query = f"{row['PlaceName']}, {row['Country']}"
    try:
        # Attempt to geocode using the combined query
        location = geocode(query)
        if location:
            return pd.Series([location.latitude, location.longitude])
        else:
            return pd.Series([None, None])
    except:
        return pd.Series([None, None])

# Apply the function to the DataFrame
coord[['latitude', 'longitude']] = coord.apply(geocode_place, axis=1)

In [ ]:
#Mapping to name of the columns to be used in javascript
rename_mapping = {
    'Name of Incident': 'NameOfIncident',
    'Type of Event': 'TypeOfEvent',
    'Place Name': 'PlaceName',
    'Affected Population': 'AffectedPopulation',
    'Important Person/Group Responsible': 'ImportantPersonGroupResponsible',
}

coord = coord.rename(columns=rename_mapping)

In [20]:
coord.to_csv('World Important Dates with Coordinates.csv', index=False, encoding='utf-8')

In [19]:
countries_freq = all['Country'].value_counts().reset_index()
countries_freq.columns = ['Country', 'Frequency']
countries_freq.head()

                    Country  Frequency
0                     India         50
1  United States of America         50
2            United Kingdom         44
3                     China         34
4                  Pakistan         31

In [21]:
# Load a country geojson file
gdf = gpd.read_file("ne_110m_admin_0_countries.geojson")

In [22]:
countries_freq['Country'] = countries_freq['Country'].str.title()
gdf['ADMIN'] = gdf['ADMIN'].str.title()

In [23]:
# Merge the geodataframe with the country frequencies
merged_gdf = gdf.merge(countries_freq, left_on='ADMIN', right_on='Country', how='left')

In [24]:
merged_gdf.head()

,scalerank,featurecla,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,ADMIN,ADM0_A3,...,LONG_LEN,ABBREV_LEN,TINY,HOMEPART,MIN_ZOOM,MIN_LABEL,MAX_LABEL,geometry,Country,Frequency
0,1,Admin-0 country,3,Afghanistan,AFG,0,2,Sovereign country,Afghanistan,AFG,...,11,4,-99,1,0.0,3.0,7.0,"POLYGON ((61.21082 35.65007, 62.23065 35.27066...",NaN,NaN
1,1,Admin-0 country,3,Angola,AGO,0,2,Sovereign country,Angola,AGO,...,6,4,-99,1,0.0,3.0,7.0,"MULTIPOLYGON (((23.90415 -11.72228, 24.07991 -...",NaN,NaN
2,1,Admin-0 country,6,Albania,ALB,0,2,Sovereign country,Albania,ALB,...,7,4,-99,1,0.0,5.0,10.0,"POLYGON ((21.02004 40.84273, 20.99999 40.58000...",NaN,NaN
3,1,Admin-0 country,4,United Arab Emirates,ARE,0,2,Sovereign country,United Arab Emirates,ARE,...,20,6,-99,1,0.0,4.0,9.0,"POLYGON ((51.57952 24.24550, 51.75744 24.29407...",NaN,NaN
4,1,Admin-0 country,2,Argentina,ARG,0,2,Sovereign country,Argentina,ARG,...,9,4,-99,1,0.0,2.0,7.0,"MULTIPOLYGON (((-66.95992 -54.89681, -67.56244...",Argentina,6.0

In [27]:
merged_gdf['Frequency'] = merged_gdf['Frequency'].fillna(0)

In [28]:
# save the updated GeoJSON file
merged_gdf.to_file("countries.geojson", driver='GeoJSON')